import { Component, OnInit } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-trivia',
  standalone: true,
  imports: [CommonModule, MatCardModule, MatButtonModule],
  templateUrl: './trivia.component.html',
  styleUrls: ['./trivia.component.scss']
})
export class TriviaComponent implements OnInit {
  triviaList: { title: string; detail: string }[] = [
    { title: "Deep Blue Defeats a Chess Champ!", detail: "In 1997, a super-smart computer named Deep Blue beat the world chess champion Garry Kasparov. Talk about brainpower!" },
    { title: "Meet Sophia, the Robot Citizen", detail: "Sophia, a robot, was granted citizenship by Saudi Arabia in 2017. A robot with a passport? Mind-blowing!" },
    { title: "AI Detects Cancer", detail: "AI can help doctors spot diseases like cancer early, sometimes better than humans. Saving lives, one scan at a time!" },
    { title: "Self-Driving Cars", detail: "Google's self-driving cars have driven over 2 million miles. Imagine doing your homework on the way to school!" },
    { title: "Gaming AI Champion", detail: "An AI trained by OpenAI crushed pro gamers in Dota 2. Who needs thumbs when you’ve got algorithms?" },
    { title: "Robot Fish to the Rescue", detail: "AI-powered robot fish swim in the ocean to track pollution. Robo-fish saving the seas!" },
    { title: "Robo Restaurants", detail: "In Japan, robots serve food and take your orders. No tipping required!" },
    { title: "AI Music Makers", detail: "AI can create music like Beethoven or Taylor Swift. Imagine your computer dropping a new hit single!" },
    { title: "Fake Conversations?", detail: "Some AI chatbots are so good at chatting, you might not realize they’re not human. Creepy or cool?" },
    { title: "Farming Like a Boss", detail: "AI-powered robots are farming pros, planting and harvesting with precision. Farming 2.0 is here!" },
    { title: "Earthquake Predictor", detail: "AI can analyze seismic data and predict earthquakes. That's science saving the day!" },
    { title: "Real-Time Translators", detail: "AI-powered apps like Google Translate can help you chat with someone in another language instantly. Say 'hola' to new friends!" },
    { title: "AI Writes Books", detail: "An AI co-wrote a book that narrates a road trip. Maybe one day it'll write YOUR biography!" },
    { title: "AI Sees It All", detail: "AI can recognize your dog breed or even tell what kind of plant is in your garden. Sherlock Holmes? More like Sherlock AI!" },
    { title: "Hey Siri, Meet Alexa", detail: "Your smart assistants aren’t just clever—they’re AI geniuses that can even recognize your voice!" },
    { title: "AI with Feelings?", detail: "Some AI can detect your emotions from your face or voice. It’s like having a digital therapist." },
    { title: "AI in Space!", detail: "NASA uses AI to help its Mars rovers explore. AI is literally out of this world!" },
    { title: "AI Beats Humans at Reading?", detail: "An AI outperformed humans in a reading test in 2018. Move over, bookworms!" },
    { title: "AI in Movies", detail: "AI helps Hollywood create amazing special effects and even bring digital actors to life. Is the Matrix real yet?" },
    { title: "Robots That Dance", detail: "AI-powered robots can bust moves better than most of us. Robot dance battle, anyone?" },
    { title: "AI Saves Wildlife", detail: "AI drones track endangered animals and fight poachers. Nature’s superhero is here!" },
    { title: "Smart X-Rays", detail: "AI can look at X-rays and spot issues faster than doctors. Super-powered vision!" },
    { title: "Painting Robots", detail: "An AI-created painting sold for $432,500. That’s one expensive robo-art!" },
    { title: "AI Writes the News", detail: "Some news articles are written by AI now. Next time you read sports updates, it might be from a robot reporter!" },
    { title: "Spy Drones in Action", detail: "AI-powered drones help soldiers in the military. Real-life Iron Man tech!" },
    { title: "Shopping Made Easy", detail: "Ever wonder how Amazon knows what you like? AI tracks your habits to suggest the coolest products." },
    { title: "Detecting Fake News", detail: "AI can spot fake news by analyzing language patterns. Truth detective in action!" },
    { title: "Predicting Music Hits", detail: "AI analyzes songs to guess which ones will go viral. It’s like the DJ of the future!" },
    { title: "AI Writes Poetry", detail: "AI can write poetry that’s funny, sweet, or even deep. Roses are red, AI is cool!" },
    { title: "Smart Prosthetics", detail: "AI helps prosthetic limbs learn movements, giving people superhuman abilities!" },
    { title: "Preventing Heart Attacks", detail: "AI can predict heart attacks before they happen. Life-saver alert!" },
    { title: "AI Digs Up History", detail: "AI helps archaeologists find ancient ruins using satellite images. Indiana Jones 2.0?" },
    { title: "Chatbots Everywhere", detail: "AI chatbots answer customer questions 24/7. They never need sleep!" },
    { title: "Voice Twins", detail: "AI can clone voices. Imagine your favorite celeb recording your voicemail message!" },
    { title: "Learning Languages", detail: "Apps like Duolingo use AI to teach you new languages. Say 'merci' to technology!" },
    { title: "Robot Bartenders", detail: "In Las Vegas, AI robots serve drinks. The future of 'cheers' is here!" },
    { title: "Saving Ecosystems", detail: "AI identifies invasive plants to protect the environment. Green thumbs gone digital!" },
    { title: "AI Wins at StarCraft", detail: "AI crushed humans in StarCraft II. Who needs gaming reflexes when you’ve got AI?" },
    { title: "Mood-Reading AI", detail: "AI can read your face to tell if you're happy, sad, or just tired of school!" },
    { title: "AI Learns You", detail: "The videos you see on YouTube are chosen by AI based on your likes. It knows you better than your best friend!" },
    { title: "Fashionista AI", detail: "AI designs clothes that match trends and your taste. The future of shopping is here!" },
    { title: "Online Scam Fighter", detail: "AI helps catch online scammers by spotting shady patterns. Internet superhero vibes!" },
    { title: "Doctor’s Assistant", detail: "AI helps doctors diagnose illnesses faster and more accurately. High-tech sidekick!" },
    { title: "Cartoon Magic", detail: "AI creates realistic animations for movies. Talk about movie magic!" },
    { title: "Memes by AI", detail: "AI can make memes. Yep, even robots understand internet humor now!" },
    { title: "Predicting Planets", detail: "AI helps NASA discover Earth-like planets. Space, here we come!" },
    { title: "Weather Wizard", detail: "AI makes weather predictions more accurate. Never get caught in the rain again!" },
    { title: "Made-Up Languages", detail: "AI once invented its own secret language, leaving its creators baffled. Robot rebellion incoming?" },
    { title: "AI in Sports", detail: "AI helps analyze player performances and predicts game outcomes. Coaches love the extra edge!" },
    { title: "Robotic Farmers", detail: "AI robots can milk cows, pick strawberries, and even plant seeds. Farm life just got futuristic!" },
    { title: "Dream AI", detail: "AI can analyze your brainwaves and predict the kind of dream you’re having. Sci-fi meets sleep science!" },
    { title: "AI in Theme Parks", detail: "Disney uses AI to design thrilling rides and manage crowd flow. Mickey’s secret tech assistant!" },
    { title: "AI for the Blind", detail: "AI apps help visually impaired people 'see' by describing their surroundings out loud. Life-changing tech!" },
    { title: "AI-Powered Makeup", detail: "AI apps let you try on makeup virtually before buying it. Beauty tech for the win!" },
    { title: "AI Meets Minecraft", detail: "AI has learned to play Minecraft and build things like castles. Digital creativity at its best!" },
    { title: "Robot Lifeguards", detail: "AI robots help patrol beaches to keep swimmers safe. Sun, sand, and sci-fi!" },
    { title: "AI Tracks Sharks", detail: "AI-powered drones spot sharks near beaches to warn swimmers. Jaws doesn’t stand a chance!" },
    { title: "Smartphones Smarter", detail: "Your phone’s AI can recognize your face, organize photos, and even suggest replies. Pocket genius!" },
    { title: "AI Tutors", detail: "AI tutoring apps explain math problems step-by-step. Homework has never been easier!" },
    { title: "Emoji Translators", detail: "AI can analyze your texts and suggest emojis to match your mood. Talk about emotional texting!" },
    { title: "AI Movie Trailers", detail: "Some movie trailers are now edited by AI. They know exactly how to grab your attention!" },
    { title: "Virtual Shopping Buddies", detail: "AI helps you find the perfect outfit or gadget online. Shopping made smarter!" },
    { title: "AI in Medicine", detail: "AI helps design new medicines faster than ever before. Tech helping health!" },
    { title: "AI-Powered Vacuums", detail: "Robots like Roomba clean your house while you relax. A dream come true!" },
    { title: "AI Creates Faces", detail: "AI can create realistic human faces that don’t belong to real people. A bit creepy, right?" },
    { title: "AI Weather Drones", detail: "AI drones track hurricanes to provide life-saving data. Storm chasers in the sky!" },
    { title: "AI Cooks", detail: "AI-powered cooking machines can whip up gourmet meals. Chef robots are here!" },
    { title: "Chatbots That Flirt", detail: "AI chatbots can flirt or tell jokes. Digital BFF or awkward bot crush?" },
    { title: "AI-Generated Video Games", detail: "AI designs levels for games like Super Mario. Endless adventures await!" },
    { title: "AI Detects Earth-Like Planets", detail: "AI scans galaxies to find planets similar to Earth. Maybe they’ve found E.T.?" },
    { title: "Robo Delivery Guys", detail: "AI-powered robots deliver food and packages in some cities. The future is at your doorstep!" },
    { title: "AI Mood Music", detail: "AI picks songs based on your mood. Feeling happy? Get a playlist to match!" },
    { title: "AI Catches Cheaters", detail: "AI tools can spot cheating during online tests. Watch out, rule-breakers!" },
    { title: "Face-Swapping Tech", detail: "AI can swap faces in videos, making hilarious or shocking clips. Deepfake fun—or danger?" },
    { title: "AI Saves Water", detail: "AI helps farmers use just the right amount of water. Earth-friendly farming!" },
    { title: "AI and Pizza", detail: "Domino’s uses AI to make sure your pizza is cooked to perfection. Tech tastes delicious!" },
    { title: "Robot Teachers?", detail: "In some places, AI robots are used as teaching assistants. Ready to learn from a bot?" },
    { title: "AI Smells Trouble", detail: "AI can identify dangerous chemicals in the air by analyzing scents. A high-tech nose!" },
    { title: "AI and Space Junk", detail: "AI tracks space debris to prevent collisions in orbit. Protecting satellites like a pro!" },
    { title: "AI Detects Lies", detail: "Some AI systems can analyze your voice and tell if you’re lying. Watch out during truth or dare!" },
    { title: "AI Identifies Music", detail: "Apps like Shazam use AI to identify songs within seconds. Name that tune, anyone?" },
    { title: "AI in Museums", detail: "AI can create virtual museum tours. Explore ancient wonders from your couch!" },
    { title: "AI Explains Science", detail: "AI creates animated videos to teach science topics. School just got cooler!" },
    { title: "AI Coaches Athletes", detail: "AI analyzes performance to help athletes improve. High-tech sports training!" },
    { title: "AI-Designed Sneakers", detail: "AI helps design stylish sneakers for brands. Fashion meets function!" },
    { title: "AI Guards Your Home", detail: "Smart home cameras with AI can recognize faces and alert you. Security level: expert!" },
    { title: "Robot Sculptors", detail: "AI robots can carve sculptures from marble. Robo-Michelangelo!" },
    { title: "AI-Powered Farming Drones", detail: "Drones guided by AI plant seeds and spray crops with precision. Farming has leveled up!" },
    { title: "AI Tracks Sports Stats", detail: "AI tracks every stat during games to help coaches strategize. Real-time insights for victory!" },
    { title: "AI Finds Fake Reviews", detail: "AI detects fake online reviews so you can trust what you read. Shopping just got safer!" },
    { title: "AI Creates Magic Tricks", detail: "AI can even invent magic tricks. Robo-magicians are here to amaze!" },
    { title: "AI-Powered Sunglasses", detail: "Smart glasses with AI can translate languages as you talk. Wearable wisdom!" },
    { title: "AI Fights Spam", detail: "AI filters spam emails so your inbox stays clean. Digital guardian angel!" },
    { title: "Robot Dog Walkers", detail: "AI robots can walk your dog. Fetch with a tech twist!" },
    { title: "AI Diagnoses Pets", detail: "AI tools help vets figure out what's wrong with sick animals. A paw-some invention!" },
    { title: "AI Dream Diary", detail: "AI can help interpret your dreams. Sweet dreams decoded!" },
    { title: "AI Draws Cartoons", detail: "AI can create animated characters that look like you. Cartoonify yourself!" },
    { title: "AI and the Oceans", detail: "AI helps track melting glaciers and rising sea levels. Keeping an eye on climate change!" },
    { title: "AI Detects Smiles", detail: "AI can analyze photos to detect if someone is smiling. Say cheese to science!" },
    { title: "AI and Space Rovers", detail: "NASA uses AI to control rovers like Perseverance on Mars. Robo-geologists on the Red Planet!" },
    { title: "AI and Butterflies", detail: "AI helps scientists track endangered butterflies by identifying species in photos. Saving the fluttery friends!" },
    { title: "AI Improves Photos", detail: "AI tools like Photoshop can fix blurry pictures and even remove photo bombers. Magic pixels!" },
    { title: "AI Solves Mazes", detail: "AI algorithms can solve the hardest mazes in seconds. Maze runner—but smarter!" },
    { title: "AI Reads Handwriting", detail: "AI can read messy handwriting, even your teacher’s scribbles! Handy for archiving notes." },
    { title: "AI in Self-Driving Cars", detail: "AI powers self-driving cars, using sensors and cameras to stay safe. The future of commuting!" },
    { title: "AI and Animal Rescue", detail: "AI drones locate animals in disaster zones to guide rescuers. Life-saving tech for furry friends!" },
    { title: "AI Writes Stories", detail: "AI can generate creative stories based on a few words. Ready to co-write your next fantasy novel?" },
    { title: "AI on the Moon", detail: "AI was used to help plan the Artemis mission to the moon. Moonwalking with a tech buddy!" },
    { title: "AI Spots Whales", detail: "AI analyzes underwater sounds to track whale movements. Helping scientists study ocean giants!" },
    { title: "AI-Powered Snow Plows", detail: "Self-driving snowplows clear streets in icy weather. No driver needed!" },
    { title: "AI Helps You Dance", detail: "AI can teach you dance moves by analyzing your steps and giving feedback. TikTok star potential!" },
    { title: "AI Makes Art", detail: "AI tools like DALL-E can create amazing digital artwork from just a description. Unleash your inner Picasso!" },
    { title: "AI Predicts Volcanic Eruptions", detail: "AI monitors volcano activity to predict eruptions. Nature’s early warning system!" },
    { title: "AI in Video Editing", detail: "AI can edit videos by automatically choosing the best scenes. YouTube just got easier!" },
    { title: "AI Spotlights Cheaters in Chess", detail: "AI tools analyze chess games to catch players who cheat using hidden apps. Checkmate!" },
    { title: "AI Finds Ancient Ruins", detail: "AI scans satellite images to discover lost ancient cities. Archaeology meets AI!" },
    { title: "AI and Candy Factories", detail: "AI ensures your favorite candy is the perfect shape and size. Sweet quality control!" },
    { title: "AI Keeps Airplanes Safe", detail: "AI checks airplane parts to make sure they're safe to fly. Your digital co-pilot!" },
    { title: "AI Weather Predictions", detail: "AI predicts weather patterns weeks ahead. Your reliable weather buddy!" },
    { title: "AI in Roller Coasters", detail: "Some roller coasters use AI to adjust speed and thrills for each ride. Extreme customization!" },
    { title: "AI and Supercomputers", detail: "AI uses powerful supercomputers to solve problems like climate change. Super brains at work!" },
    { title: "AI Translates Sign Language", detail: "AI apps convert sign language into spoken words in real time. Breaking communication barriers!" },
    { title: "AI Designs Furniture", detail: "AI helps create comfy and stylish chairs and sofas. Who knew tech had an eye for design?" },
    { title: "AI Builds Bridges", detail: "AI ensures bridges are strong and safe during construction. Engineering at its smartest!" },
    { title: "AI and Jellyfish", detail: "AI-powered robots swim like jellyfish to explore fragile ocean reefs. Robo-sea creatures!" },
    { title: "AI Diagnoses Plant Diseases", detail: "Farmers use AI to identify plant diseases and save crops. A techy green thumb!" },
    { title: "AI Creates Digital Avatars", detail: "AI tools can make an animated version of you for games or videos. Your cartoon twin!" },
    { title: "AI Makes Learning Fun", detail: "Educational games powered by AI adapt to your skills, keeping lessons fun and challenging!" },
    { title: "AI Detects Earthquakes", detail: "AI systems spot early signs of earthquakes to alert people faster. Tech saving lives!" },
    { title: "AI-Designed LEGO Sets", detail: "LEGO uses AI to design creative and challenging sets for fans. Build the future brick by brick!" },
    { title: "AI in Chat Apps", detail: "AI powers auto-suggestions when you type texts or emails. Your digital mind reader!" },
    { title: "AI Spots Meteors", detail: "AI scans the skies for meteors heading toward Earth. Cosmic protectors in action!" },
    { title: "AI Guides Space Robots", detail: "AI helps robots explore asteroids for valuable minerals. Space mining is here!" },
    { title: "AI Saves Coral Reefs", detail: "AI tracks coral health and restores damaged reefs. Tech diving deep to save oceans!" },
    { title: "AI and Personalized Fashion", detail: "AI apps recommend outfits based on your style. Virtual shopping assistants are trending!" },
    { title: "AI Writes Movie Scripts", detail: "AI can generate story ideas for Hollywood blockbusters. Future Oscar winner?" },
    { title: "AI-Powered Footballs", detail: "Smart footballs with AI sensors track throws and catches for better training. Perfect spirals ahead!" },
    { title: "AI Helps Bees", detail: "AI drones pollinate flowers like bees. A backup plan for nature!" },
    { title: "AI Detects Fake News", detail: "AI identifies misleading news online to help you stay informed. Truth over lies!" },
    { title: "AI Helps Build Roller Coasters", detail: "AI ensures rides are thrilling and safe. Roller coasters designed to perfection!" },
    { title: "AI Analyzes Sports Replays", detail: "AI spots fouls and game-winning plays in real-time. The ultimate referee!" },
    { title: "AI in Forest Conservation", detail: "AI analyzes forests to prevent illegal logging. Tech guarding the green!" },
    { title: "AI Creates 3D Models", detail: "AI turns 2D drawings into 3D designs for games or movies. From sketch to screen!" },
    { title: "AI and Paper Airplanes", detail: "AI simulations can design the ultimate paper airplane for long flights. Next-level folding!" },
    { title: "AI in Concerts", detail: "AI light shows sync with music at concerts for jaw-dropping visuals. Dancing with the lights!" },
    { title: "AI in Emergency Rooms", detail: "AI helps doctors diagnose faster during emergencies. A lifesaving partner in hospitals!" },
    { title: "AI for Better Sleep", detail: "AI apps track your sleep and recommend bedtime routines. Snooze smarter!" }
];

  selectedTrivia: { title: string; detail: string }[] = [];

  ngOnInit() {
    this.loadRandomTrivia();
  }

  loadRandomTrivia() {
    this.selectedTrivia = [];
    const triviaCopy = [...this.triviaList]; // Copy to avoid modifying the original list
    for (let i = 0; i < 3; i++) {
      const randomIndex = Math.floor(Math.random() * triviaCopy.length);
      this.selectedTrivia.push(triviaCopy.splice(randomIndex, 1)[0]);
    }
  }
}
